name: HelpfulTools
description: Tools that are helpful
version: ${project.version}
api-version: 1.14
author: FluffyBear
depend: [Slimefun]
softdepend: [SlimyTreeTaps]
main: me.fluffybear.helpfultools.HelpfulTools